apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamo-deployment-cluster-role
rules:
- apiGroups: ["nvidia.com"]
  resources: ["dynamodeployments"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynamo-deployment-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: dynamo-cloud-dynamo-api-store
  namespace: dynamo-cloud
roleRef:
  kind: ClusterRole
  name: dynamo-deployment-cluster-role
  apiGroup: rbac.authorization.k8s.io
