apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamo-deployer
  namespace: dynamo-cloud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dynamo-deployment-role
  namespace: dynamo-cloud
rules:
- apiGroups: ["nvidia.com"]
  resources: ["dynamodeployments"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynamo-deployment-rolebinding
  namespace: dynamo-cloud
subjects:
- kind: ServiceAccount
  name: dynamo-deployer
  namespace: dynamo-cloud
- kind: ServiceAccount
  name: dynamo-cloud-dynamo-api-store
  namespace: dynamo-cloud
roleRef:
  kind: Role
  name: dynamo-deployment-role
  apiGroup: rbac.authorization.k8s.io
