apiVersion: v1
kind: Service
metadata:
  name: dynamo-store
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: dynamo-api-store
  publishNotReadyAddresses: true
